### ISSUE TITLE
Link ERROR

### ISSUE THREAD

**Issue by pratik-p** [pratik-p/Ts3-Message-Tool#1]
```
1>------ Build started: Project: test_plugin, Configuration: Release x64 ------
1>plugin.cpp
1>   Creating library C:\Users\Stinger\Desktop\poke script\pluginsdk\src\x64\Release\test_plugin.lib and object C:\Users\Stinger\Desktop\poke script\pluginsdk\src\x64\Release\test_plugin.exp
1>plugin.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QString::~QString(void)" (__imp_??1QString@@QEAA@XZ) referenced in function "char * __cdecl openDialog(void)" (?openDialog@@YAPEADXZ)
1>plugin.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class QString __cdecl QString::fromLatin1(char const *,int)" (__imp_?fromLatin1@QString@@SA?AV1@PEBDH@Z) referenced in function "char * __cdecl openDialog(void)" (?openDialog@@YAPEADXZ)
1>plugin.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl QString::toInt(bool *,int)const " (__imp_?toInt@QString@@QEBAHPEA_NH@Z) referenced in function "char * __cdecl openDialog(void)" (?openDialog@@YAPEADXZ)
1>plugin.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QString::QString(struct QString::Null const &)" (__imp_??0QString@@QEAA@AEBUNull@0@@Z) referenced in function "char * __cdecl openDialog(void)" (?openDialog@@YAPEADXZ)
1>plugin.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class QString __cdecl QInputDialog::getText(class QWidget *,class QString const &,class QString const &,enum QLineEdit::EchoMode,class QString const &,bool *,class QFlags<enum Qt::WindowType>,class QFlags<enum Qt::InputMethodHint>)" (__imp_?getText@QInputDialog@@SA?AVQString@@PEAVQWidget@@AEBV2@1W4EchoMode@QLineEdit@@1PEA_NV?$QFlags@W4WindowType@Qt@@@@V?$QFlags@W4InputMethodHint@Qt@@@@@Z) referenced in function "char * __cdecl openDialog(void)" (?openDialog@@YAPEADXZ)
1>plugin.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static struct QString::Null const QString::null" (__imp_?null@QString@@2UNull@1@B)
1>C:\Users\Stinger\Desktop\poke script\pluginsdk\src\x64\Release\test_plugin.dll : fatal error LNK1120: 6 unresolved externals
1>Done building project "test_plugin.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by pratik-p** [comment]
Using:
- Windows 10
- Visual Studio 2017 edition
- Qt  5.6.1: https://download.qt.io/official_releases/qt/5.6/5.6.1/qt-opensource-windows-x86-msvc2013_64-5.6.1.exe.mirrorlist
-

**Comment by Bluscream** [comment]
Why so complicated? https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/massAction/__init__.py#L69

**Comment by dehesselle** [comment]
First, some general thoughts/recommendations:

- TeamSpeak 3.1.x is built with Qt 5.6.1 and VisualStudio 2015. You should use VS2015 as well as the according msvc2015-5.6.1 build of Qt.
- I recommend you use Qt Creator if you want to develop GUI applications with Qt. The IDE is perfectly fitted for Qt development and works out of the box if VS2015 is already installed (it autodetects the MSVC compiler, no manual setup required). Of course you may disregard this recommendation and choose whatever you tools you like - but I can only help you with the things I know and use.
- My setup is Windows 10, Qt 5.6.1 msvc2015_64-5.6.1 and Qt Creator using the compiler from VS2015 (community edition).

That being said, I created a project with Qt Creator and turned your code into a working prototype, showcasing a simple custom dialog. I made a few minor adjustments to make it compile but left everything else as it was. (I did not solve your original link error!)

Screenshots:
http://imgur.com/a/6BXAO
http://imgur.com/a/hHdxH
http://imgur.com/a/dXyxs

**Final thoughts**
This is *your* project, you may choose to do with it as you like. Don't feel obligated to merge my PR if you want to go into another direction (I won't be offended). But I do have a personal request: please don't remove it from GitHub (I noticed you removed "Calendar"). The reason I ask for this is simple: I do not have any interest/motivation to help people with their private/closed source projects. It's either "we all share and help each other" or "nothing" for me. One day some other guy might be looking for something on GitHub just like you did, and he'll be glad to find as much projects/examples/... as possible. So please do not make me regret helping random people on the Internet.

**Comment by pratik-p** [comment]
@dehesselle 
Really appreciate that you took the time out to help me. I spent some time reviewing what you sent and said. I'm still unsure what is causing that link error, but your suggestion to use the Qt Creator was great and I was able to finish the project.

Again thanks a ton!

**Comment by dehesselle** [comment]
That's awesome - you're welcome! Cheers! 😃
